import sys
from awsglue.transforms import *
from awsglue.utils import getResolvedOptions
from pyspark.context import SparkContext
from awsglue.context import GlueContext
from awsglue.job import Job

# Custom
import boto3
from datetime import datetime
from awsglue.dynamicframe import DynamicFrame
from pyspark.sql.functions import lit

args = getResolvedOptions(sys.argv, ["JOB_NAME"])
sc = SparkContext()
glueContext = GlueContext(sc)
spark = glueContext.spark_session
job = Job(glueContext)
job.init(args["JOB_NAME"], args)

# Script generated for node AccountAdServer
AccountAdServer_node1657711956506 = glueContext.create_dynamic_frame.from_catalog(
    database="dev-sf-db",
    table_name="salesforce_account_ad_server",
    transformation_ctx="AccountAdServer_node1657711956506",
)

# Script generated for node user
user_node1657711873175 = glueContext.create_dynamic_frame.from_catalog(
    database="dev-sf-db",
    table_name="salesforce_user",
    transformation_ctx="user_node1657711873175",
)

# Script generated for node MediaPlanPlacement
MediaPlanPlacement_node1657712485639 = glueContext.create_dynamic_frame.from_catalog(
    database="dev-sf-db",
    table_name="salesforce_media_plan_placement",
    transformation_ctx="MediaPlanPlacement_node1657712485639",
)

# Script generated for node QuoteLineItem
QuoteLineItem_node1657712563745 = glueContext.create_dynamic_frame.from_catalog(
    database="dev-sf-db",
    table_name="salesforce_quote_line_item",
    transformation_ctx="QuoteLineItem_node1657712563745",
)

# Script generated for node RenamedUser
RenamedUser_node1657712118442 = ApplyMapping.apply(
    frame=user_node1657711873175,
    mappings=[
        ("id", "string", "`(u) id`", "string"),
        ("username", "string", "`(u) username`", "string"),
        ("lastname", "string", "`(u) lastname`", "string"),
        ("firstname", "string", "`(u) firstname`", "string"),
        ("middlename", "string", "`(u) middlename`", "string"),
        ("suffix", "string", "`(u) suffix`", "string"),
        ("name", "string", "`(u) name`", "string"),
        ("companyname", "string", "`(u) companyname`", "string"),
        ("division", "string", "`(u) division`", "string"),
        ("department", "string", "`(u) department`", "string"),
        ("title", "string", "`(u) title`", "string"),
        ("street", "string", "`(u) street`", "string"),
        ("city", "string", "`(u) city`", "string"),
        ("state", "string", "`(u) state`", "string"),
        ("postalcode", "string", "`(u) postalcode`", "string"),
        ("country", "string", "`(u) country`", "string"),
        ("latitude", "string", "`(u) latitude`", "string"),
        ("longitude", "string", "`(u) longitude`", "string"),
        ("geocodeaccuracy", "string", "`(u) geocodeaccuracy`", "string"),
        ("address", "string", "`(u) address`", "string"),
        ("email", "string", "`(u) email`", "string"),
        (
            "emailpreferencesautobcc",
            "string",
            "`(u) emailpreferencesautobcc`",
            "string",
        ),
        (
            "emailpreferencesautobccstayintouch",
            "string",
            "`(u) emailpreferencesautobccstayintouch`",
            "string",
        ),
        (
            "emailpreferencesstayintouchreminder",
            "string",
            "`(u) emailpreferencesstayintouchreminder`",
            "string",
        ),
        ("senderemail", "string", "`(u) senderemail`", "string"),
        ("sendername", "string", "`(u) sendername`", "string"),
        ("signature", "string", "`(u) signature`", "string"),
        ("stayintouchsubject", "string", "`(u) stayintouchsubject`", "string"),
        ("stayintouchsignature", "string", "`(u) stayintouchsignature`", "string"),
        ("stayintouchnote", "string", "`(u) stayintouchnote`", "string"),
        ("phone", "string", "`(u) phone`", "string"),
        ("fax", "string", "`(u) fax`", "string"),
        ("mobilephone", "string", "`(u) mobilephone`", "string"),
        ("alias", "string", "`(u) alias`", "string"),
        ("communitynickname", "string", "`(u) communitynickname`", "string"),
        ("badgetext", "string", "`(u) badgetext`", "string"),
        ("isactive", "string", "`(u) isactive`", "string"),
        ("timezonesidkey", "string", "`(u) timezonesidkey`", "string"),
        ("userroleid", "string", "`(u) userroleid`", "string"),
        ("localesidkey", "string", "`(u) localesidkey`", "string"),
        ("receivesinfoemails", "string", "`(u) receivesinfoemails`", "string"),
        (
            "receivesadmininfoemails",
            "string",
            "`(u) receivesadmininfoemails`",
            "string",
        ),
        ("emailencodingkey", "string", "`(u) emailencodingkey`", "string"),
        ("profileid", "string", "`(u) profileid`", "string"),
        ("usertype", "string", "`(u) usertype`", "string"),
        ("languagelocalekey", "string", "`(u) languagelocalekey`", "string"),
        ("employeenumber", "string", "`(u) employeenumber`", "string"),
        ("delegatedapproverid", "string", "`(u) delegatedapproverid`", "string"),
        ("managerid", "string", "`(u) managerid`", "string"),
        ("lastlogindate", "string", "`(u) lastlogindate`", "string"),
        ("lastpasswordchangedate", "string", "`(u) lastpasswordchangedate`", "string"),
        ("createddate", "string", "`(u) createddate`", "string"),
        ("createdbyid", "string", "`(u) createdbyid`", "string"),
        ("lastmodifieddate", "string", "`(u) lastmodifieddate`", "string"),
        ("lastmodifiedbyid", "string", "`(u) lastmodifiedbyid`", "string"),
        ("systemmodstamp", "string", "`(u) systemmodstamp`", "string"),
        ("numberoffailedlogins", "string", "`(u) numberoffailedlogins`", "string"),
        (
            "offlinetrialexpirationdate",
            "string",
            "`(u) offlinetrialexpirationdate`",
            "string",
        ),
        (
            "offlinepdatrialexpirationdate",
            "string",
            "`(u) offlinepdatrialexpirationdate`",
            "string",
        ),
        (
            "userpermissionsmarketinguser",
            "string",
            "`(u) userpermissionsmarketinguser`",
            "string",
        ),
        (
            "userpermissionsofflineuser",
            "string",
            "`(u) userpermissionsofflineuser`",
            "string",
        ),
        (
            "userpermissionsavantgouser",
            "string",
            "`(u) userpermissionsavantgouser`",
            "string",
        ),
        (
            "userpermissionscallcenterautologin",
            "string",
            "`(u) userpermissionscallcenterautologin`",
            "string",
        ),
        (
            "userpermissionssfcontentuser",
            "string",
            "`(u) userpermissionssfcontentuser`",
            "string",
        ),
        (
            "userpermissionsknowledgeuser",
            "string",
            "`(u) userpermissionsknowledgeuser`",
            "string",
        ),
        (
            "userpermissionsinteractionuser",
            "string",
            "`(u) userpermissionsinteractionuser`",
            "string",
        ),
        (
            "userpermissionssupportuser",
            "string",
            "`(u) userpermissionssupportuser`",
            "string",
        ),
        ("forecastenabled", "string", "`(u) forecastenabled`", "string"),
        (
            "userpreferencesactivityreminderspopup",
            "string",
            "`(u) userpreferencesactivityreminderspopup`",
            "string",
        ),
        (
            "userpreferenceseventreminderscheckboxdefault",
            "string",
            "`(u) userpreferenceseventreminderscheckboxdefault`",
            "string",
        ),
        (
            "userpreferencestaskreminderscheckboxdefault",
            "string",
            "`(u) userpreferencestaskreminderscheckboxdefault`",
            "string",
        ),
        (
            "userpreferencesremindersoundoff",
            "string",
            "`(u) userpreferencesremindersoundoff`",
            "string",
        ),
        (
            "userpreferencesdisableallfeedsemail",
            "string",
            "`(u) userpreferencesdisableallfeedsemail`",
            "string",
        ),
        (
            "userpreferencesdisablefollowersemail",
            "string",
            "`(u) userpreferencesdisablefollowersemail`",
            "string",
        ),
        (
            "userpreferencesdisableprofilepostemail",
            "string",
            "`(u) userpreferencesdisableprofilepostemail`",
            "string",
        ),
        (
            "userpreferencesdisablechangecommentemail",
            "string",
            "`(u) userpreferencesdisablechangecommentemail`",
            "string",
        ),
        (
            "userpreferencesdisablelatercommentemail",
            "string",
            "`(u) userpreferencesdisablelatercommentemail`",
            "string",
        ),
        (
            "userpreferencesdisprofpostcommentemail",
            "string",
            "`(u) userpreferencesdisprofpostcommentemail`",
            "string",
        ),
        (
            "userpreferencescontentnoemail",
            "string",
            "`(u) userpreferencescontentnoemail`",
            "string",
        ),
        (
            "userpreferencescontentemailasandwhen",
            "string",
            "`(u) userpreferencescontentemailasandwhen`",
            "string",
        ),
        (
            "userpreferencesapexpagesdevelopermode",
            "string",
            "`(u) userpreferencesapexpagesdevelopermode`",
            "string",
        ),
        (
            "userpreferencesreceivenonotificationsasapprover",
            "string",
            "`(u) userpreferencesreceivenonotificationsasapprover`",
            "string",
        ),
        (
            "userpreferencesreceivenotificationsasdelegatedapprover",
            "string",
            "`(u) userpreferencesreceivenotificationsasdelegatedapprover`",
            "string",
        ),
        (
            "userpreferenceshidecsngetchattermobiletask",
            "string",
            "`(u) userpreferenceshidecsngetchattermobiletask`",
            "string",
        ),
        (
            "userpreferencesdisablementionspostemail",
            "string",
            "`(u) userpreferencesdisablementionspostemail`",
            "string",
        ),
        (
            "userpreferencesdismentionscommentemail",
            "string",
            "`(u) userpreferencesdismentionscommentemail`",
            "string",
        ),
        (
            "userpreferenceshidecsndesktoptask",
            "string",
            "`(u) userpreferenceshidecsndesktoptask`",
            "string",
        ),
        (
            "userpreferenceshidechatteronboardingsplash",
            "string",
            "`(u) userpreferenceshidechatteronboardingsplash`",
            "string",
        ),
        (
            "userpreferenceshidesecondchatteronboardingsplash",
            "string",
            "`(u) userpreferenceshidesecondchatteronboardingsplash`",
            "string",
        ),
        (
            "userpreferencesdiscommentafterlikeemail",
            "string",
            "`(u) userpreferencesdiscommentafterlikeemail`",
            "string",
        ),
        (
            "userpreferencesdisablelikeemail",
            "string",
            "`(u) userpreferencesdisablelikeemail`",
            "string",
        ),
        (
            "userpreferencessortfeedbycomment",
            "string",
            "`(u) userpreferencessortfeedbycomment`",
            "string",
        ),
        (
            "userpreferencesdisablemessageemail",
            "string",
            "`(u) userpreferencesdisablemessageemail`",
            "string",
        ),
        (
            "userpreferencesdisablebookmarkemail",
            "string",
            "`(u) userpreferencesdisablebookmarkemail`",
            "string",
        ),
        (
            "userpreferencesdisablesharepostemail",
            "string",
            "`(u) userpreferencesdisablesharepostemail`",
            "string",
        ),
        (
            "userpreferencesenableautosubforfeeds",
            "string",
            "`(u) userpreferencesenableautosubforfeeds`",
            "string",
        ),
        (
            "userpreferencesdisablefilesharenotificationsforapi",
            "string",
            "`(u) userpreferencesdisablefilesharenotificationsforapi`",
            "string",
        ),
        (
            "userpreferencesshowtitletoexternalusers",
            "string",
            "`(u) userpreferencesshowtitletoexternalusers`",
            "string",
        ),
        (
            "userpreferencesshowmanagertoexternalusers",
            "string",
            "`(u) userpreferencesshowmanagertoexternalusers`",
            "string",
        ),
        (
            "userpreferencesshowemailtoexternalusers",
            "string",
            "`(u) userpreferencesshowemailtoexternalusers`",
            "string",
        ),
        (
            "userpreferencesshowworkphonetoexternalusers",
            "string",
            "`(u) userpreferencesshowworkphonetoexternalusers`",
            "string",
        ),
        (
            "userpreferencesshowmobilephonetoexternalusers",
            "string",
            "`(u) userpreferencesshowmobilephonetoexternalusers`",
            "string",
        ),
        (
            "userpreferencesshowfaxtoexternalusers",
            "string",
            "`(u) userpreferencesshowfaxtoexternalusers`",
            "string",
        ),
        (
            "userpreferencesshowstreetaddresstoexternalusers",
            "string",
            "`(u) userpreferencesshowstreetaddresstoexternalusers`",
            "string",
        ),
        (
            "userpreferencesshowcitytoexternalusers",
            "string",
            "`(u) userpreferencesshowcitytoexternalusers`",
            "string",
        ),
        (
            "userpreferencesshowstatetoexternalusers",
            "string",
            "`(u) userpreferencesshowstatetoexternalusers`",
            "string",
        ),
        (
            "userpreferencesshowpostalcodetoexternalusers",
            "string",
            "`(u) userpreferencesshowpostalcodetoexternalusers`",
            "string",
        ),
        (
            "userpreferencesshowcountrytoexternalusers",
            "string",
            "`(u) userpreferencesshowcountrytoexternalusers`",
            "string",
        ),
        (
            "userpreferencesshowprofilepictoguestusers",
            "string",
            "`(u) userpreferencesshowprofilepictoguestusers`",
            "string",
        ),
        (
            "userpreferencesshowtitletoguestusers",
            "string",
            "`(u) userpreferencesshowtitletoguestusers`",
            "string",
        ),
        (
            "userpreferencesshowcitytoguestusers",
            "string",
            "`(u) userpreferencesshowcitytoguestusers`",
            "string",
        ),
        (
            "userpreferencesshowstatetoguestusers",
            "string",
            "`(u) userpreferencesshowstatetoguestusers`",
            "string",
        ),
        (
            "userpreferencesshowpostalcodetoguestusers",
            "string",
            "`(u) userpreferencesshowpostalcodetoguestusers`",
            "string",
        ),
        (
            "userpreferencesshowcountrytoguestusers",
            "string",
            "`(u) userpreferencesshowcountrytoguestusers`",
            "string",
        ),
        (
            "userpreferenceshideinvoicesredirectconfirmation",
            "string",
            "`(u) userpreferenceshideinvoicesredirectconfirmation`",
            "string",
        ),
        (
            "userpreferenceshidestatementsredirectconfirmation",
            "string",
            "`(u) userpreferenceshidestatementsredirectconfirmation`",
            "string",
        ),
        (
            "userpreferenceshides1browserui",
            "string",
            "`(u) userpreferenceshides1browserui`",
            "string",
        ),
        (
            "userpreferencesdisableendorsementemail",
            "string",
            "`(u) userpreferencesdisableendorsementemail`",
            "string",
        ),
        (
            "userpreferencespathassistantcollapsed",
            "string",
            "`(u) userpreferencespathassistantcollapsed`",
            "string",
        ),
        (
            "userpreferencescachediagnostics",
            "string",
            "`(u) userpreferencescachediagnostics`",
            "string",
        ),
        (
            "userpreferencesshowemailtoguestusers",
            "string",
            "`(u) userpreferencesshowemailtoguestusers`",
            "string",
        ),
        (
            "userpreferencesshowmanagertoguestusers",
            "string",
            "`(u) userpreferencesshowmanagertoguestusers`",
            "string",
        ),
        (
            "userpreferencesshowworkphonetoguestusers",
            "string",
            "`(u) userpreferencesshowworkphonetoguestusers`",
            "string",
        ),
        (
            "userpreferencesshowmobilephonetoguestusers",
            "string",
            "`(u) userpreferencesshowmobilephonetoguestusers`",
            "string",
        ),
        (
            "userpreferencesshowfaxtoguestusers",
            "string",
            "`(u) userpreferencesshowfaxtoguestusers`",
            "string",
        ),
        (
            "userpreferencesshowstreetaddresstoguestusers",
            "string",
            "`(u) userpreferencesshowstreetaddresstoguestusers`",
            "string",
        ),
        (
            "userpreferenceslightningexperiencepreferred",
            "string",
            "`(u) userpreferenceslightningexperiencepreferred`",
            "string",
        ),
        (
            "userpreferencespreviewlightning",
            "string",
            "`(u) userpreferencespreviewlightning`",
            "string",
        ),
        (
            "userpreferenceshideenduseronboardingassistantmodal",
            "string",
            "`(u) userpreferenceshideenduseronboardingassistantmodal`",
            "string",
        ),
        (
            "userpreferenceshidelightningmigrationmodal",
            "string",
            "`(u) userpreferenceshidelightningmigrationmodal`",
            "string",
        ),
        (
            "userpreferenceshidesfxwelcomemat",
            "string",
            "`(u) userpreferenceshidesfxwelcomemat`",
            "string",
        ),
        (
            "userpreferenceshidebiggerphotocallout",
            "string",
            "`(u) userpreferenceshidebiggerphotocallout`",
            "string",
        ),
        (
            "userpreferencesglobalnavbarwtshown",
            "string",
            "`(u) userpreferencesglobalnavbarwtshown`",
            "string",
        ),
        (
            "userpreferencesglobalnavgridmenuwtshown",
            "string",
            "`(u) userpreferencesglobalnavgridmenuwtshown`",
            "string",
        ),
        (
            "userpreferencescreatelexappswtshown",
            "string",
            "`(u) userpreferencescreatelexappswtshown`",
            "string",
        ),
        (
            "userpreferencesfavoriteswtshown",
            "string",
            "`(u) userpreferencesfavoriteswtshown`",
            "string",
        ),
        (
            "userpreferencesrecordhomesectioncollapsewtshown",
            "string",
            "`(u) userpreferencesrecordhomesectioncollapsewtshown`",
            "string",
        ),
        (
            "userpreferencesrecordhomereservedwtshown",
            "string",
            "`(u) userpreferencesrecordhomereservedwtshown`",
            "string",
        ),
        (
            "userpreferencesfavoritesshowtopfavorites",
            "string",
            "`(u) userpreferencesfavoritesshowtopfavorites`",
            "string",
        ),
        (
            "userpreferencesexcludemailappattachments",
            "string",
            "`(u) userpreferencesexcludemailappattachments`",
            "string",
        ),
        (
            "userpreferencessuppresstasksfxreminders",
            "string",
            "`(u) userpreferencessuppresstasksfxreminders`",
            "string",
        ),
        (
            "userpreferencessuppresseventsfxreminders",
            "string",
            "`(u) userpreferencessuppresseventsfxreminders`",
            "string",
        ),
        (
            "userpreferencespreviewcustomtheme",
            "string",
            "`(u) userpreferencespreviewcustomtheme`",
            "string",
        ),
        (
            "userpreferenceshascelebrationbadge",
            "string",
            "`(u) userpreferenceshascelebrationbadge`",
            "string",
        ),
        (
            "userpreferencesuserdebugmodepref",
            "string",
            "`(u) userpreferencesuserdebugmodepref`",
            "string",
        ),
        (
            "userpreferencessrhoverrideactivities",
            "string",
            "`(u) userpreferencessrhoverrideactivities`",
            "string",
        ),
        (
            "userpreferencesnewlightningreportrunpageenabled",
            "string",
            "`(u) userpreferencesnewlightningreportrunpageenabled`",
            "string",
        ),
        (
            "userpreferencesnativeemailclient",
            "string",
            "`(u) userpreferencesnativeemailclient`",
            "string",
        ),
        (
            "userpreferenceshidebrowseproductredirectconfirmation",
            "string",
            "`(u) userpreferenceshidebrowseproductredirectconfirmation`",
            "string",
        ),
        ("contactid", "string", "`(u) contactid`", "string"),
        ("accountid", "string", "`(u) accountid`", "string"),
        ("callcenterid", "string", "`(u) callcenterid`", "string"),
        ("extension", "string", "`(u) extension`", "string"),
        ("federationidentifier", "string", "`(u) federationidentifier`", "string"),
        ("aboutme", "string", "`(u) aboutme`", "string"),
        ("fullphotourl", "string", "`(u) fullphotourl`", "string"),
        ("smallphotourl", "string", "`(u) smallphotourl`", "string"),
        ("isextindicatorvisible", "string", "`(u) isextindicatorvisible`", "string"),
        ("outofofficemessage", "string", "`(u) outofofficemessage`", "string"),
        ("mediumphotourl", "string", "`(u) mediumphotourl`", "string"),
        ("digestfrequency", "string", "`(u) digestfrequency`", "string"),
        (
            "defaultgroupnotificationfrequency",
            "string",
            "`(u) defaultgroupnotificationfrequency`",
            "string",
        ),
        ("lastvieweddate", "string", "`(u) lastvieweddate`", "string"),
        ("lastreferenceddate", "string", "`(u) lastreferenceddate`", "string"),
        ("bannerphotourl", "string", "`(u) bannerphotourl`", "string"),
        ("smallbannerphotourl", "string", "`(u) smallbannerphotourl`", "string"),
        ("mediumbannerphotourl", "string", "`(u) mediumbannerphotourl`", "string"),
        ("isprofilephotoactive", "string", "`(u) isprofilephotoactive`", "string"),
        ("individualid", "string", "`(u) individualid`", "string"),
        (
            "vlocity_cmt__docusignemail__c",
            "string",
            "`(u) vlocity_cmt__docusignemail__c`",
            "string",
        ),
        (
            "vlocity_cmt__globalkey__c",
            "string",
            "`(u) vlocity_cmt__globalkey__c`",
            "string",
        ),
        (
            "vlocity_cmt__omplussyncenabled__c",
            "string",
            "`(u) vlocity_cmt__omplussyncenabled__c`",
            "string",
        ),
        (
            "vlocity_cmt__omplus_enabled__c",
            "string",
            "`(u) vlocity_cmt__omplus_enabled__c`",
            "string",
        ),
        (
            "vlocity_cmt__storeassociatestatus__c",
            "string",
            "`(u) vlocity_cmt__storeassociatestatus__c`",
            "string",
        ),
        ("filename", "string", "`(u) filename`", "string"),
        ("function_name", "string", "`(u) function_name`", "string"),
        ("function_version", "string", "`(u) function_version`", "string"),
        ("aws_request_id", "string", "`(u) aws_request_id`", "string"),
        ("appflow_id", "string", "`(u) appflow_id`", "string"),
        ("processed_ts", "timestamp", "`(u) processed_ts`", "timestamp"),
        ("usergroup__c", "string", "`(u) usergroup__c`", "string"),
        (
            "userpermissionsliveagentuser",
            "string",
            "`(u) userpermissionsliveagentuser`",
            "string",
        ),
        ("sales_office__c", "string", "`(u) sales_office__c`", "string"),
        (
            "neilon__is_s3_link_user__c",
            "string",
            "`(u) neilon__is_s3_link_user__c`",
            "string",
        ),
        (
            "xfiles__amazon_iam_secret__c",
            "string",
            "`(u) xfiles__amazon_iam_secret__c`",
            "string",
        ),
        (
            "xfiles__amazon_iam_key__c",
            "string",
            "`(u) xfiles__amazon_iam_key__c`",
            "string",
        ),
        ("partition_0", "string", "`(u) partition_0`", "string"),
        ("partition_1", "string", "`(u) partition_1`", "string"),
        ("partition_2", "string", "`(u) partition_2`", "string"),
        ("partition_3", "string", "`(u) partition_3`", "string"),
    ],
    transformation_ctx="RenamedUser_node1657712118442",
)

# Script generated for node RenamedQuoteLineItem
RenamedQuoteLineItem_node1657712672668 = ApplyMapping.apply(
    frame=QuoteLineItem_node1657712563745,
    mappings=[
        ("id", "string", "`(qli) id`", "string"),
        ("isdeleted", "string", "`(qli) isdeleted`", "string"),
        ("linenumber", "string", "`(qli) linenumber`", "string"),
        ("createddate", "string", "`(qli) createddate`", "string"),
        ("createdbyid", "string", "`(qli) createdbyid`", "string"),
        ("lastmodifieddate", "string", "`(qli) lastmodifieddate`", "string"),
        ("lastmodifiedbyid", "string", "`(qli) lastmodifiedbyid`", "string"),
        ("systemmodstamp", "string", "`(qli) systemmodstamp`", "string"),
        ("lastvieweddate", "string", "`(qli) lastvieweddate`", "string"),
        ("lastreferenceddate", "string", "`(qli) lastreferenceddate`", "string"),
        ("quoteid", "string", "`(qli) quoteid`", "string"),
        ("pricebookentryid", "string", "`(qli) pricebookentryid`", "string"),
        ("opportunitylineitemid", "string", "`(qli) opportunitylineitemid`", "string"),
        ("quantity", "string", "`(qli) quantity`", "string"),
        ("unitprice", "string", "`(qli) unitprice`", "string"),
        ("discount", "string", "`(qli) discount`", "string"),
        ("hasrevenueschedule", "string", "`(qli) hasrevenueschedule`", "string"),
        ("hasquantityschedule", "string", "`(qli) hasquantityschedule`", "string"),
        ("description", "string", "`(qli) description`", "string"),
        ("servicedate", "string", "`(qli) servicedate`", "string"),
        ("product2id", "string", "`(qli) product2id`", "string"),
        ("sortorder", "string", "`(qli) sortorder`", "string"),
        ("hasschedule", "string", "`(qli) hasschedule`", "string"),
        ("listprice", "string", "`(qli) listprice`", "string"),
        ("subtotal", "string", "`(qli) subtotal`", "string"),
        ("totalprice", "string", "`(qli) totalprice`", "string"),
        (
            "vlocity_cmt__action__c",
            "string",
            "`(qli) vlocity_cmt__action__c`",
            "string",
        ),
        (
            "vlocity_cmt__assetid__c",
            "string",
            "`(qli) vlocity_cmt__assetid__c`",
            "string",
        ),
        (
            "vlocity_cmt__assetreferenceid__c",
            "string",
            "`(qli) vlocity_cmt__assetreferenceid__c`",
            "string",
        ),
        (
            "vlocity_cmt__asyncoperation__c",
            "string",
            "`(qli) vlocity_cmt__asyncoperation__c`",
            "string",
        ),
        (
            "vlocity_cmt__attributemetadatachanges__c",
            "string",
            "`(qli) vlocity_cmt__attributemetadatachanges__c`",
            "string",
        ),
        (
            "vlocity_cmt__attributeselectedvalues__c",
            "string",
            "`(qli) vlocity_cmt__attributeselectedvalues__c`",
            "string",
        ),
        (
            "vlocity_cmt__baseonetimecharge__c",
            "string",
            "`(qli) vlocity_cmt__baseonetimecharge__c`",
            "string",
        ),
        (
            "vlocity_cmt__baseonetimetotal__c",
            "string",
            "`(qli) vlocity_cmt__baseonetimetotal__c`",
            "string",
        ),
        (
            "vlocity_cmt__baserecurringcharge__c",
            "string",
            "`(qli) vlocity_cmt__baserecurringcharge__c`",
            "string",
        ),
        (
            "vlocity_cmt__baserecurringtotal__c",
            "string",
            "`(qli) vlocity_cmt__baserecurringtotal__c`",
            "string",
        ),
        (
            "vlocity_cmt__billingaccountid__c",
            "string",
            "`(qli) vlocity_cmt__billingaccountid__c`",
            "string",
        ),
        (
            "vlocity_cmt__catalogitemreferencedatetime__c",
            "string",
            "`(qli) vlocity_cmt__catalogitemreferencedatetime__c`",
            "string",
        ),
        (
            "vlocity_cmt__connectdate__c",
            "string",
            "`(qli) vlocity_cmt__connectdate__c`",
            "string",
        ),
        (
            "vlocity_cmt__cpqcardinalitymessage__c",
            "string",
            "`(qli) vlocity_cmt__cpqcardinalitymessage__c`",
            "string",
        ),
        (
            "vlocity_cmt__cpqmessagedata__c",
            "string",
            "`(qli) vlocity_cmt__cpqmessagedata__c`",
            "string",
        ),
        (
            "vlocity_cmt__cpqpricingmessage__c",
            "string",
            "`(qli) vlocity_cmt__cpqpricingmessage__c`",
            "string",
        ),
        (
            "vlocity_cmt__currencypaymentmode__c",
            "string",
            "`(qli) vlocity_cmt__currencypaymentmode__c`",
            "string",
        ),
        (
            "vlocity_cmt__disconnectdate__c",
            "string",
            "`(qli) vlocity_cmt__disconnectdate__c`",
            "string",
        ),
        (
            "vlocity_cmt__effectivebaseonetimetotal__c",
            "string",
            "`(qli) vlocity_cmt__effectivebaseonetimetotal__c`",
            "string",
        ),
        (
            "vlocity_cmt__effectivebaserecurringtotal__c",
            "string",
            "`(qli) vlocity_cmt__effectivebaserecurringtotal__c`",
            "string",
        ),
        (
            "vlocity_cmt__effectiveonetimecosttotal__c",
            "string",
            "`(qli) vlocity_cmt__effectiveonetimecosttotal__c`",
            "string",
        ),
        (
            "vlocity_cmt__effectiveonetimeloyaltytotal__c",
            "string",
            "`(qli) vlocity_cmt__effectiveonetimeloyaltytotal__c`",
            "string",
        ),
        (
            "vlocity_cmt__effectiveonetimetotal__c",
            "string",
            "`(qli) vlocity_cmt__effectiveonetimetotal__c`",
            "string",
        ),
        (
            "vlocity_cmt__effectivequantity__c",
            "string",
            "`(qli) vlocity_cmt__effectivequantity__c`",
            "string",
        ),
        (
            "vlocity_cmt__effectiverecurringcosttotal__c",
            "string",
            "`(qli) vlocity_cmt__effectiverecurringcosttotal__c`",
            "string",
        ),
        (
            "vlocity_cmt__effectiverecurringtotal__c",
            "string",
            "`(qli) vlocity_cmt__effectiverecurringtotal__c`",
            "string",
        ),
        (
            "vlocity_cmt__effectiveusagecosttotal__c",
            "string",
            "`(qli) vlocity_cmt__effectiveusagecosttotal__c`",
            "string",
        ),
        (
            "vlocity_cmt__effectiveusagepricetotal__c",
            "string",
            "`(qli) vlocity_cmt__effectiveusagepricetotal__c`",
            "string",
        ),
        (
            "vlocity_cmt__effectiveusagequantity__c",
            "string",
            "`(qli) vlocity_cmt__effectiveusagequantity__c`",
            "string",
        ),
        (
            "vlocity_cmt__filter__c",
            "string",
            "`(qli) vlocity_cmt__filter__c`",
            "string",
        ),
        (
            "vlocity_cmt__financedamounttotal__c",
            "string",
            "`(qli) vlocity_cmt__financedamounttotal__c`",
            "string",
        ),
        (
            "vlocity_cmt__financedamount__c",
            "string",
            "`(qli) vlocity_cmt__financedamount__c`",
            "string",
        ),
        (
            "vlocity_cmt__financedinstallmentamount__c",
            "string",
            "`(qli) vlocity_cmt__financedinstallmentamount__c`",
            "string",
        ),
        (
            "vlocity_cmt__incartquantitymap__c",
            "string",
            "`(qli) vlocity_cmt__incartquantitymap__c`",
            "string",
        ),
        (
            "vlocity_cmt__ispriced__c",
            "string",
            "`(qli) vlocity_cmt__ispriced__c`",
            "string",
        ),
        (
            "vlocity_cmt__isproducttrackagreement__c",
            "string",
            "`(qli) vlocity_cmt__isproducttrackagreement__c`",
            "string",
        ),
        (
            "vlocity_cmt__isvalidated__c",
            "string",
            "`(qli) vlocity_cmt__isvalidated__c`",
            "string",
        ),
        (
            "vlocity_cmt__itemname__c",
            "string",
            "`(qli) vlocity_cmt__itemname__c`",
            "string",
        ),
        (
            "vlocity_cmt__jsonattribute__c",
            "string",
            "`(qli) vlocity_cmt__jsonattribute__c`",
            "string",
        ),
        (
            "vlocity_cmt__jsonnode__c",
            "string",
            "`(qli) vlocity_cmt__jsonnode__c`",
            "string",
        ),
        (
            "vlocity_cmt__lastpricedat__c",
            "string",
            "`(qli) vlocity_cmt__lastpricedat__c`",
            "string",
        ),
        (
            "vlocity_cmt__linenumber__c",
            "string",
            "`(qli) vlocity_cmt__linenumber__c`",
            "string",
        ),
        (
            "vlocity_cmt__lockedby__c",
            "string",
            "`(qli) vlocity_cmt__lockedby__c`",
            "string",
        ),
        (
            "vlocity_cmt__lockedfor__c",
            "string",
            "`(qli) vlocity_cmt__lockedfor__c`",
            "string",
        ),
        (
            "vlocity_cmt__modification__c",
            "string",
            "`(qli) vlocity_cmt__modification__c`",
            "string",
        ),
        (
            "vlocity_cmt__onetimecalculatedprice__c",
            "string",
            "`(qli) vlocity_cmt__onetimecalculatedprice__c`",
            "string",
        ),
        (
            "vlocity_cmt__onetimecharge__c",
            "string",
            "`(qli) vlocity_cmt__onetimecharge__c`",
            "string",
        ),
        (
            "vlocity_cmt__onetimecosttotal__c",
            "string",
            "`(qli) vlocity_cmt__onetimecosttotal__c`",
            "string",
        ),
        (
            "vlocity_cmt__onetimecost__c",
            "string",
            "`(qli) vlocity_cmt__onetimecost__c`",
            "string",
        ),
        (
            "vlocity_cmt__onetimediscountprice__c",
            "string",
            "`(qli) vlocity_cmt__onetimediscountprice__c`",
            "string",
        ),
        (
            "vlocity_cmt__onetimeloyaltyprice__c",
            "string",
            "`(qli) vlocity_cmt__onetimeloyaltyprice__c`",
            "string",
        ),
        (
            "vlocity_cmt__onetimeloyaltytotal__c",
            "string",
            "`(qli) vlocity_cmt__onetimeloyaltytotal__c`",
            "string",
        ),
        (
            "vlocity_cmt__onetimemanualdiscount__c",
            "string",
            "`(qli) vlocity_cmt__onetimemanualdiscount__c`",
            "string",
        ),
        (
            "vlocity_cmt__onetimemargin__c",
            "string",
            "`(qli) vlocity_cmt__onetimemargin__c`",
            "string",
        ),
        (
            "vlocity_cmt__onetimetotal__c",
            "string",
            "`(qli) vlocity_cmt__onetimetotal__c`",
            "string",
        ),
        (
            "vlocity_cmt__overagecalculatedprice__c",
            "string",
            "`(qli) vlocity_cmt__overagecalculatedprice__c`",
            "string",
        ),
        (
            "vlocity_cmt__overagecharge__c",
            "string",
            "`(qli) vlocity_cmt__overagecharge__c`",
            "string",
        ),
        (
            "vlocity_cmt__overagediscountprice__c",
            "string",
            "`(qli) vlocity_cmt__overagediscountprice__c`",
            "string",
        ),
        (
            "vlocity_cmt__overagemanualdiscount__c",
            "string",
            "`(qli) vlocity_cmt__overagemanualdiscount__c`",
            "string",
        ),
        (
            "vlocity_cmt__overagetotal__c",
            "string",
            "`(qli) vlocity_cmt__overagetotal__c`",
            "string",
        ),
        (
            "vlocity_cmt__overageuom__c",
            "string",
            "`(qli) vlocity_cmt__overageuom__c`",
            "string",
        ),
        (
            "vlocity_cmt__parentitemid__c",
            "string",
            "`(qli) vlocity_cmt__parentitemid__c`",
            "string",
        ),
        (
            "vlocity_cmt__premisesid__c",
            "string",
            "`(qli) vlocity_cmt__premisesid__c`",
            "string",
        ),
        (
            "vlocity_cmt__pricinglogdata__c",
            "string",
            "`(qli) vlocity_cmt__pricinglogdata__c`",
            "string",
        ),
        (
            "vlocity_cmt__priorquotelineitemid__c",
            "string",
            "`(qli) vlocity_cmt__priorquotelineitemid__c`",
            "string",
        ),
        (
            "vlocity_cmt__product2id__c",
            "string",
            "`(qli) vlocity_cmt__product2id__c`",
            "string",
        ),
        (
            "vlocity_cmt__productattribxn__c",
            "string",
            "`(qli) vlocity_cmt__productattribxn__c`",
            "string",
        ),
        (
            "vlocity_cmt__productgroupkey__c",
            "string",
            "`(qli) vlocity_cmt__productgroupkey__c`",
            "string",
        ),
        (
            "vlocity_cmt__producthierarchygroupkeypath__c",
            "string",
            "`(qli) vlocity_cmt__producthierarchygroupkeypath__c`",
            "string",
        ),
        (
            "vlocity_cmt__producthierarchypath__c",
            "string",
            "`(qli) vlocity_cmt__producthierarchypath__c`",
            "string",
        ),
        (
            "vlocity_cmt__provisioningstatus__c",
            "string",
            "`(qli) vlocity_cmt__provisioningstatus__c`",
            "string",
        ),
        ("vlocity_cmt__query__c", "string", "`(qli) vlocity_cmt__query__c`", "string"),
        (
            "vlocity_cmt__quotegroupid__c",
            "string",
            "`(qli) vlocity_cmt__quotegroupid__c`",
            "string",
        ),
        (
            "vlocity_cmt__quotememberid__c",
            "string",
            "`(qli) vlocity_cmt__quotememberid__c`",
            "string",
        ),
        (
            "vlocity_cmt__recurringcalculatedprice__c",
            "string",
            "`(qli) vlocity_cmt__recurringcalculatedprice__c`",
            "string",
        ),
        (
            "vlocity_cmt__recurringcharge__c",
            "string",
            "`(qli) vlocity_cmt__recurringcharge__c`",
            "string",
        ),
        (
            "vlocity_cmt__recurringcosttotal__c",
            "string",
            "`(qli) vlocity_cmt__recurringcosttotal__c`",
            "string",
        ),
        (
            "vlocity_cmt__recurringcost__c",
            "string",
            "`(qli) vlocity_cmt__recurringcost__c`",
            "string",
        ),
        (
            "vlocity_cmt__recurringdiscountprice__c",
            "string",
            "`(qli) vlocity_cmt__recurringdiscountprice__c`",
            "string",
        ),
        (
            "vlocity_cmt__recurringmanualdiscount__c",
            "string",
            "`(qli) vlocity_cmt__recurringmanualdiscount__c`",
            "string",
        ),
        (
            "vlocity_cmt__recurringmargin__c",
            "string",
            "`(qli) vlocity_cmt__recurringmargin__c`",
            "string",
        ),
        (
            "vlocity_cmt__recurringtotal__c",
            "string",
            "`(qli) vlocity_cmt__recurringtotal__c`",
            "string",
        ),
        (
            "vlocity_cmt__recurringuom__c",
            "string",
            "`(qli) vlocity_cmt__recurringuom__c`",
            "string",
        ),
        (
            "vlocity_cmt__recurring_uom__c",
            "string",
            "`(qli) vlocity_cmt__recurring_uom__c`",
            "string",
        ),
        (
            "vlocity_cmt__relationshiptype__c",
            "string",
            "`(qli) vlocity_cmt__relationshiptype__c`",
            "string",
        ),
        (
            "vlocity_cmt__reliesonitemid__c",
            "string",
            "`(qli) vlocity_cmt__reliesonitemid__c`",
            "string",
        ),
        (
            "vlocity_cmt__rootitemid__c",
            "string",
            "`(qli) vlocity_cmt__rootitemid__c`",
            "string",
        ),
        (
            "vlocity_cmt__sequencenumber__c",
            "string",
            "`(qli) vlocity_cmt__sequencenumber__c`",
            "string",
        ),
        (
            "vlocity_cmt__serialnumber__c",
            "string",
            "`(qli) vlocity_cmt__serialnumber__c`",
            "string",
        ),
        (
            "vlocity_cmt__serviceaccountid__c",
            "string",
            "`(qli) vlocity_cmt__serviceaccountid__c`",
            "string",
        ),
        (
            "vlocity_cmt__servicedate__c",
            "string",
            "`(qli) vlocity_cmt__servicedate__c`",
            "string",
        ),
        (
            "vlocity_cmt__serviceidentifier__c",
            "string",
            "`(qli) vlocity_cmt__serviceidentifier__c`",
            "string",
        ),
        (
            "vlocity_cmt__servicepointid__c",
            "string",
            "`(qli) vlocity_cmt__servicepointid__c`",
            "string",
        ),
        (
            "vlocity_cmt__sourcelinenumber__c",
            "string",
            "`(qli) vlocity_cmt__sourcelinenumber__c`",
            "string",
        ),
        (
            "vlocity_cmt__subaction__c",
            "string",
            "`(qli) vlocity_cmt__subaction__c`",
            "string",
        ),
        (
            "vlocity_cmt__subscriptionid__c",
            "string",
            "`(qli) vlocity_cmt__subscriptionid__c`",
            "string",
        ),
        (
            "vlocity_cmt__usagecosttotal__c",
            "string",
            "`(qli) vlocity_cmt__usagecosttotal__c`",
            "string",
        ),
        (
            "vlocity_cmt__usagemargin__c",
            "string",
            "`(qli) vlocity_cmt__usagemargin__c`",
            "string",
        ),
        (
            "vlocity_cmt__usagemeasurementid__c",
            "string",
            "`(qli) vlocity_cmt__usagemeasurementid__c`",
            "string",
        ),
        (
            "vlocity_cmt__usagepricetotal__c",
            "string",
            "`(qli) vlocity_cmt__usagepricetotal__c`",
            "string",
        ),
        (
            "vlocity_cmt__usagequantity__c",
            "string",
            "`(qli) vlocity_cmt__usagequantity__c`",
            "string",
        ),
        (
            "vlocity_cmt__usageunitcost__c",
            "string",
            "`(qli) vlocity_cmt__usageunitcost__c`",
            "string",
        ),
        (
            "vlocity_cmt__usageunitprice__c",
            "string",
            "`(qli) vlocity_cmt__usageunitprice__c`",
            "string",
        ),
        (
            "vlocity_cmt__validationdate__c",
            "string",
            "`(qli) vlocity_cmt__validationdate__c`",
            "string",
        ),
        (
            "swm_discounting_exception__c",
            "string",
            "`(qli) swm_discounting_exception__c`",
            "string",
        ),
        (
            "swm_gross_unit_cost__c",
            "string",
            "`(qli) swm_gross_unit_cost__c`",
            "string",
        ),
        ("is_bonus_product__c", "string", "`(qli) is_bonus_product__c`", "string"),
        ("swm_market_price__c", "string", "`(qli) swm_market_price__c`", "string"),
        ("swm_floor_rate__c", "string", "`(qli) swm_floor_rate__c`", "string"),
        ("swm_rate_card__c", "string", "`(qli) swm_rate_card__c`", "string"),
        ("parent_qli__c", "string", "`(qli) parent_qli__c`", "string"),
        ("targeting_premium__c", "string", "`(qli) targeting_premium__c`", "string"),
        (
            "gross_unit_cost_with_premium__c",
            "string",
            "`(qli) gross_unit_cost_with_premium__c`",
            "string",
        ),
        (
            "swm_sponsorship_product__c",
            "string",
            "`(qli) swm_sponsorship_product__c`",
            "string",
        ),
        ("buy_type__c", "string", "`(qli) buy_type__c`", "string"),
        ("filename", "string", "`(qli) filename`", "string"),
        ("function_name", "string", "`(qli) function_name`", "string"),
        ("function_version", "string", "`(qli) function_version`", "string"),
        ("aws_request_id", "string", "`(qli) aws_request_id`", "string"),
        ("appflow_id", "string", "`(qli) appflow_id`", "string"),
        ("processed_ts", "timestamp", "`(qli) processed_ts`", "timestamp"),
        ("swm_optimize__c", "string", "`(qli) swm_optimize__c`", "string"),
        ("swm_read_optimize__c", "string", "`(qli) swm_read_optimize__c`", "string"),
        (
            "swm_total_market_price__c",
            "string",
            "`(qli) swm_total_market_price__c`",
            "string",
        ),
        ("swm_gst__c", "string", "`(qli) swm_gst__c`", "string"),
        ("swm_otc_gst__c", "string", "`(qli) swm_otc_gst__c`", "string"),
        ("swm_gst_value__c", "string", "`(qli) swm_gst_value__c`", "string"),
        ("production_system__c", "string", "`(qli) production_system__c`", "string"),
        ("impliedtotal__c", "string", "`(qli) impliedtotal__c`", "string"),
        ("totaladtime__c", "string", "`(qli) totaladtime__c`", "string"),
        ("bonus_ad_time__c", "string", "`(qli) bonus_ad_time__c`", "string"),
        ("costperratingpoint__c", "string", "`(qli) costperratingpoint__c`", "string"),
        ("grossratingpoint__c", "string", "`(qli) grossratingpoint__c`", "string"),
        ("paidadtime__c", "string", "`(qli) paidadtime__c`", "string"),
        ("swm_is_sponsorship__c", "string", "`(qli) swm_is_sponsorship__c`", "string"),
        (
            "is_roadblock_product__c",
            "string",
            "`(qli) is_roadblock_product__c`",
            "string",
        ),
        (
            "swm_approval_status__c",
            "string",
            "`(qli) swm_approval_status__c`",
            "string",
        ),
        ("swm_quote_owner__c", "string", "`(qli) swm_quote_owner__c`", "string"),
        ("swm_prior_oli_id__c", "string", "`(qli) swm_prior_oli_id__c`", "string"),
        ("partition_0", "string", "`(qli) partition_0`", "string"),
        ("partition_1", "string", "`(qli) partition_1`", "string"),
        ("partition_2", "string", "`(qli) partition_2`", "string"),
        ("partition_3", "string", "`(qli) partition_3`", "string"),
    ],
    transformation_ctx="RenamedQuoteLineItem_node1657712672668",
)

# Script generated for node Join
Join_node1657712000396 = Join.apply(
    frame1=AccountAdServer_node1657711956506,
    frame2=RenamedUser_node1657712118442,
    keys1=["createdbyid"],
    keys2=["`(u) id`"],
    transformation_ctx="Join_node1657712000396",
)

# Script generated for node MppJoinQuoteLineItem
MppJoinQuoteLineItem_node1657712646978 = Join.apply(
    frame1=MediaPlanPlacement_node1657712485639,
    frame2=RenamedQuoteLineItem_node1657712672668,
    keys1=["vlocity_cmt__quotelineitemid__c"],
    keys2=["`(qli) id`"],
    transformation_ctx="MppJoinQuoteLineItem_node1657712646978",
)

# Script generated for node RenamedMppQuoteLineItem
RenamedMppQuoteLineItem_node1657713309822 = ApplyMapping.apply(
    frame=MppJoinQuoteLineItem_node1657712646978,
    mappings=[
        ("id", "string", "`(mppNqli) id`", "string"),
        ("isdeleted", "string", "`(mppNqli) isdeleted`", "string"),
        ("name", "string", "`(mppNqli) name`", "string"),
        ("createddate", "string", "`(mppNqli) createddate`", "string"),
        ("createdbyid", "string", "`(mppNqli) createdbyid`", "string"),
        ("lastmodifieddate", "string", "`(mppNqli) lastmodifieddate`", "string"),
        ("lastmodifiedbyid", "string", "`(mppNqli) lastmodifiedbyid`", "string"),
        ("systemmodstamp", "string", "`(mppNqli) systemmodstamp`", "string"),
        ("lastactivitydate", "string", "`(mppNqli) lastactivitydate`", "string"),
        ("lastvieweddate", "string", "`(mppNqli) lastvieweddate`", "string"),
        ("lastreferenceddate", "string", "`(mppNqli) lastreferenceddate`", "string"),
        (
            "vlocity_cmt__quoteid__c",
            "string",
            "`(mppNqli) vlocity_cmt__quoteid__c`",
            "string",
        ),
        (
            "vlocity_cmt__adbleedamountuom__c",
            "string",
            "`(mppNqli) vlocity_cmt__adbleedamountuom__c`",
            "string",
        ),
        (
            "vlocity_cmt__adbleedamount__c",
            "string",
            "`(mppNqli) vlocity_cmt__adbleedamount__c`",
            "string",
        ),
        (
            "vlocity_cmt__adcreativesizetypes__c",
            "string",
            "`(mppNqli) vlocity_cmt__adcreativesizetypes__c`",
            "string",
        ),
        (
            "vlocity_cmt__adcreativeurl__c",
            "string",
            "`(mppNqli) vlocity_cmt__adcreativeurl__c`",
            "string",
        ),
        (
            "vlocity_cmt__adplacementprioritytype__c",
            "string",
            "`(mppNqli) vlocity_cmt__adplacementprioritytype__c`",
            "string",
        ),
        (
            "vlocity_cmt__adrequestedenddate__c",
            "string",
            "`(mppNqli) vlocity_cmt__adrequestedenddate__c`",
            "string",
        ),
        (
            "vlocity_cmt__adrequestedstartdate__c",
            "string",
            "`(mppNqli) vlocity_cmt__adrequestedstartdate__c`",
            "string",
        ),
        (
            "vlocity_cmt__adspacespecificationadserver__c",
            "string",
            "`(mppNqli) vlocity_cmt__adspacespecificationadserver__c`",
            "string",
        ),
        (
            "vlocity_cmt__adspacespecificationid__c",
            "string",
            "`(mppNqli) vlocity_cmt__adspacespecificationid__c`",
            "string",
        ),
        (
            "vlocity_cmt__adspacespecificationmediaproperty__c",
            "string",
            "`(mppNqli) vlocity_cmt__adspacespecificationmediaproperty__c`",
            "string",
        ),
        (
            "vlocity_cmt__adspacespecificationtype__c",
            "string",
            "`(mppNqli) vlocity_cmt__adspacespecificationtype__c`",
            "string",
        ),
        (
            "vlocity_cmt__adtimeperepisode__c",
            "string",
            "`(mppNqli) vlocity_cmt__adtimeperepisode__c`",
            "string",
        ),
        (
            "vlocity_cmt__bonusadtime__c",
            "string",
            "`(mppNqli) vlocity_cmt__bonusadtime__c`",
            "string",
        ),
        (
            "vlocity_cmt__costperratingpoint__c",
            "string",
            "`(mppNqli) vlocity_cmt__costperratingpoint__c`",
            "string",
        ),
        (
            "vlocity_cmt__customerdaypart__c",
            "string",
            "`(mppNqli) vlocity_cmt__customerdaypart__c`",
            "string",
        ),
        (
            "vlocity_cmt__grossratingpoint__c",
            "string",
            "`(mppNqli) vlocity_cmt__grossratingpoint__c`",
            "string",
        ),
        (
            "vlocity_cmt__impliedrate__c",
            "string",
            "`(mppNqli) vlocity_cmt__impliedrate__c`",
            "string",
        ),
        (
            "vlocity_cmt__impliedtotal__c",
            "string",
            "`(mppNqli) vlocity_cmt__impliedtotal__c`",
            "string",
        ),
        (
            "vlocity_cmt__isadbleedenabled__c",
            "string",
            "`(mppNqli) vlocity_cmt__isadbleedenabled__c`",
            "string",
        ),
        (
            "vlocity_cmt__maximumfrequencyinterval__c",
            "string",
            "`(mppNqli) vlocity_cmt__maximumfrequencyinterval__c`",
            "string",
        ),
        (
            "vlocity_cmt__maximumfrequency__c",
            "string",
            "`(mppNqli) vlocity_cmt__maximumfrequency__c`",
            "string",
        ),
        (
            "vlocity_cmt__maximumuserfrequencyinterval__c",
            "string",
            "`(mppNqli) vlocity_cmt__maximumuserfrequencyinterval__c`",
            "string",
        ),
        (
            "vlocity_cmt__maximumuserfrequency__c",
            "string",
            "`(mppNqli) vlocity_cmt__maximumuserfrequency__c`",
            "string",
        ),
        (
            "vlocity_cmt__mediatype__c",
            "string",
            "`(mppNqli) vlocity_cmt__mediatype__c`",
            "string",
        ),
        (
            "vlocity_cmt__paidadtime__c",
            "string",
            "`(mppNqli) vlocity_cmt__paidadtime__c`",
            "string",
        ),
        (
            "vlocity_cmt__quotelineitemid__c",
            "string",
            "`(mppNqli) vlocity_cmt__quotelineitemid__c`",
            "string",
        ),
        (
            "vlocity_cmt__quotelineitemonetimecharge__c",
            "string",
            "`(mppNqli) vlocity_cmt__quotelineitemonetimecharge__c`",
            "string",
        ),
        (
            "vlocity_cmt__quotelineitemonetimetotal__c",
            "string",
            "`(mppNqli) vlocity_cmt__quotelineitemonetimetotal__c`",
            "string",
        ),
        (
            "vlocity_cmt__quotelineitemproductcode__c",
            "string",
            "`(mppNqli) vlocity_cmt__quotelineitemproductcode__c`",
            "string",
        ),
        (
            "vlocity_cmt__quotelineitemquantity__c",
            "string",
            "`(mppNqli) vlocity_cmt__quotelineitemquantity__c`",
            "string",
        ),
        (
            "vlocity_cmt__sponsorshiptype__c",
            "string",
            "`(mppNqli) vlocity_cmt__sponsorshiptype__c`",
            "string",
        ),
        (
            "vlocity_cmt__targetingparameters__c",
            "string",
            "`(mppNqli) vlocity_cmt__targetingparameters__c`",
            "string",
        ),
        (
            "vlocity_cmt__totaladtime__c",
            "string",
            "`(mppNqli) vlocity_cmt__totaladtime__c`",
            "string",
        ),
        (
            "vlocity_cmt__userengagementgoaltype__c",
            "string",
            "`(mppNqli) vlocity_cmt__userengagementgoaltype__c`",
            "string",
        ),
        (
            "vlocity_cmt__userengagementgoalunittype__c",
            "string",
            "`(mppNqli) vlocity_cmt__userengagementgoalunittype__c`",
            "string",
        ),
        (
            "vlocity_cmt__userengagementgoalunit__c",
            "string",
            "`(mppNqli) vlocity_cmt__userengagementgoalunit__c`",
            "string",
        ),
        (
            "swm_gross_unit_cost__c",
            "string",
            "`(mppNqli) swm_gross_unit_cost__c`",
            "string",
        ),
        (
            "swm_baseonetimecharge__c",
            "string",
            "`(mppNqli) swm_baseonetimecharge__c`",
            "string",
        ),
        ("swm_status__c", "string", "`(mppNqli) swm_status__c`", "string"),
        ("swm_market_price__c", "string", "`(mppNqli) swm_market_price__c`", "string"),
        ("swm_floor_rate__c", "string", "`(mppNqli) swm_floor_rate__c`", "string"),
        ("swm_product_name__c", "string", "`(mppNqli) swm_product_name__c`", "string"),
        (
            "production_system__c",
            "string",
            "`(mppNqli) production_system__c`",
            "string",
        ),
        ("cost_method__c", "string", "`(mppNqli) cost_method__c`", "string"),
        ("unit_type__c", "string", "`(mppNqli) unit_type__c`", "string"),
        (
            "swm_inventory_status__c",
            "string",
            "`(mppNqli) swm_inventory_status__c`",
            "string",
        ),
        (
            "swm_sponsorship_product__c",
            "string",
            "`(mppNqli) swm_sponsorship_product__c`",
            "string",
        ),
        ("swm_inventory__c", "string", "`(mppNqli) swm_inventory__c`", "string"),
        ("is_bonus_product__c", "string", "`(mppNqli) is_bonus_product__c`", "string"),
        ("swm_expiry_date__c", "string", "`(mppNqli) swm_expiry_date__c`", "string"),
        ("platform__c", "string", "`(mppNqli) platform__c`", "string"),
        (
            "swm_calendar_details__c",
            "string",
            "`(mppNqli) swm_calendar_details__c`",
            "string",
        ),
        ("quote_owner__c", "string", "`(mppNqli) quote_owner__c`", "string"),
        ("swm_is_gam__c", "string", "`(mppNqli) swm_is_gam__c`", "string"),
        (
            "swm_adcreativesizetypejson__c",
            "string",
            "`(mppNqli) swm_adcreativesizetypejson__c`",
            "string",
        ),
        (
            "swm_overbook_inventory__c",
            "string",
            "`(mppNqli) swm_overbook_inventory__c`",
            "string",
        ),
        (
            "swm_sponsorship_booking__c",
            "string",
            "`(mppNqli) swm_sponsorship_booking__c`",
            "string",
        ),
        (
            "swm_extended_till__c",
            "string",
            "`(mppNqli) swm_extended_till__c`",
            "string",
        ),
        (
            "swm_no_of_times_extended__c",
            "string",
            "`(mppNqli) swm_no_of_times_extended__c`",
            "string",
        ),
        ("swm_is_extended__c", "string", "`(mppNqli) swm_is_extended__c`", "string"),
        ("delete_datetime__c", "string", "`(mppNqli) delete_datetime__c`", "string"),
        (
            "inventory_status_history__c",
            "string",
            "`(mppNqli) inventory_status_history__c`",
            "string",
        ),
        (
            "swm_extend_hold_count__c",
            "string",
            "`(mppNqli) swm_extend_hold_count__c`",
            "string",
        ),
        (
            "sponsorship_inventory_email_reminder__c",
            "string",
            "`(mppNqli) sponsorship_inventory_email_reminder__c`",
            "string",
        ),
        (
            "sponsorship_inventory_release_date__c",
            "string",
            "`(mppNqli) sponsorship_inventory_release_date__c`",
            "string",
        ),
        (
            "swm_extended_release__c",
            "string",
            "`(mppNqli) swm_extended_release__c`",
            "string",
        ),
        (
            "swm_approval_status__c",
            "string",
            "`(mppNqli) swm_approval_status__c`",
            "string",
        ),
        ("swm_is_exempt__c", "string", "`(mppNqli) swm_is_exempt__c`", "string"),
        (
            "swm_parent_media_placement__c",
            "string",
            "`(mppNqli) swm_parent_media_placement__c`",
            "string",
        ),
        ("swm_product_type__c", "string", "`(mppNqli) swm_product_type__c`", "string"),
        ("filename", "string", "`(mppNqli) filename`", "string"),
        ("function_name", "string", "`(mppNqli) function_name`", "string"),
        ("function_version", "string", "`(mppNqli) function_version`", "string"),
        ("aws_request_id", "string", "`(mppNqli) aws_request_id`", "string"),
        ("appflow_id", "string", "`(mppNqli) appflow_id`", "string"),
        ("processed_ts", "timestamp", "`(mppNqli) processed_ts`", "timestamp"),
        (
            "swm_campaign_manager__c",
            "string",
            "`(mppNqli) swm_campaign_manager__c`",
            "string",
        ),
        ("swm_cm_gam_id__c", "string", "`(mppNqli) swm_cm_gam_id__c`", "string"),
        (
            "swm_line_item_family__c",
            "string",
            "`(mppNqli) swm_line_item_family__c`",
            "string",
        ),
        (
            "swm_custom_targetings__c",
            "string",
            "`(mppNqli) swm_custom_targetings__c`",
            "string",
        ),
        ("swm_optimise__c", "string", "`(mppNqli) swm_optimise__c`", "string"),
        ("swm_optimize__c", "string", "`(mppNqli) swm_optimize__c`", "string"),
        (
            "swm_available_units__c",
            "string",
            "`(mppNqli) swm_available_units__c`",
            "string",
        ),
        (
            "swm_reserved_units__c",
            "string",
            "`(mppNqli) swm_reserved_units__c`",
            "string",
        ),
        (
            "swm_gam_unit_type__c",
            "string",
            "`(mppNqli) swm_gam_unit_type__c`",
            "string",
        ),
        ("revenue_type__c", "string", "`(mppNqli) revenue_type__c`", "string"),
        ("swm_description__c", "string", "`(mppNqli) swm_description__c`", "string"),
        ("swm_sov__c", "string", "`(mppNqli) swm_sov__c`", "string"),
        (
            "swm_non_billable_value__c",
            "string",
            "`(mppNqli) swm_non_billable_value__c`",
            "string",
        ),
        (
            "swm_consolidate_targeting__c",
            "string",
            "`(mppNqli) swm_consolidate_targeting__c`",
            "string",
        ),
        ("approval_status__c", "string", "`(mppNqli) approval_status__c`", "string"),
        (
            "sme_allow_overbooking__c",
            "string",
            "`(mppNqli) sme_allow_overbooking__c`",
            "string",
        ),
        ("partition_0", "string", "`(mppNqli) partition_0`", "string"),
        ("partition_1", "string", "`(mppNqli) partition_1`", "string"),
        ("partition_2", "string", "`(mppNqli) partition_2`", "string"),
        ("partition_3", "string", "`(mppNqli) partition_3`", "string"),
        ("`(qli) id`", "string", "`(mppNqli) (qli) id`", "string"),
        ("`(qli) isdeleted`", "string", "`(mppNqli) (qli) isdeleted`", "string"),
        ("`(qli) linenumber`", "string", "`(mppNqli) (qli) linenumber`", "string"),
        ("`(qli) createddate`", "string", "`(mppNqli) (qli) createddate`", "string"),
        ("`(qli) createdbyid`", "string", "`(mppNqli) (qli) createdbyid`", "string"),
        (
            "`(qli) lastmodifieddate`",
            "string",
            "`(mppNqli) (qli) lastmodifieddate`",
            "string",
        ),
        (
            "`(qli) lastmodifiedbyid`",
            "string",
            "`(mppNqli) (qli) lastmodifiedbyid`",
            "string",
        ),
        (
            "`(qli) systemmodstamp`",
            "string",
            "`(mppNqli) (qli) systemmodstamp`",
            "string",
        ),
        (
            "`(qli) lastvieweddate`",
            "string",
            "`(mppNqli) (qli) lastvieweddate`",
            "string",
        ),
        (
            "`(qli) lastreferenceddate`",
            "string",
            "`(mppNqli) (qli) lastreferenceddate`",
            "string",
        ),
        ("`(qli) quoteid`", "string", "`(mppNqli) (qli) quoteid`", "string"),
        (
            "`(qli) pricebookentryid`",
            "string",
            "`(mppNqli) (qli) pricebookentryid`",
            "string",
        ),
        (
            "`(qli) opportunitylineitemid`",
            "string",
            "`(mppNqli) (qli) opportunitylineitemid`",
            "string",
        ),
        ("`(qli) quantity`", "string", "`(mppNqli) (qli) quantity`", "string"),
        ("`(qli) unitprice`", "string", "`(mppNqli) (qli) unitprice`", "string"),
        ("`(qli) discount`", "string", "`(mppNqli) (qli) discount`", "string"),
        (
            "`(qli) hasrevenueschedule`",
            "string",
            "`(mppNqli) (qli) hasrevenueschedule`",
            "string",
        ),
        (
            "`(qli) hasquantityschedule`",
            "string",
            "`(mppNqli) (qli) hasquantityschedule`",
            "string",
        ),
        ("`(qli) description`", "string", "`(mppNqli) (qli) description`", "string"),
        ("`(qli) servicedate`", "string", "`(mppNqli) (qli) servicedate`", "string"),
        ("`(qli) product2id`", "string", "`(mppNqli) (qli) product2id`", "string"),
        ("`(qli) sortorder`", "string", "`(mppNqli) (qli) sortorder`", "string"),
        ("`(qli) hasschedule`", "string", "`(mppNqli) (qli) hasschedule`", "string"),
        ("`(qli) listprice`", "string", "`(mppNqli) (qli) listprice`", "string"),
        ("`(qli) subtotal`", "string", "`(mppNqli) (qli) subtotal`", "string"),
        ("`(qli) totalprice`", "string", "`(mppNqli) (qli) totalprice`", "string"),
        (
            "`(qli) vlocity_cmt__action__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__action__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__assetid__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__assetid__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__assetreferenceid__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__assetreferenceid__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__asyncoperation__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__asyncoperation__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__attributemetadatachanges__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__attributemetadatachanges__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__attributeselectedvalues__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__attributeselectedvalues__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__baseonetimecharge__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__baseonetimecharge__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__baseonetimetotal__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__baseonetimetotal__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__baserecurringcharge__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__baserecurringcharge__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__baserecurringtotal__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__baserecurringtotal__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__billingaccountid__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__billingaccountid__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__catalogitemreferencedatetime__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__catalogitemreferencedatetime__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__connectdate__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__connectdate__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__cpqcardinalitymessage__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__cpqcardinalitymessage__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__cpqmessagedata__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__cpqmessagedata__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__cpqpricingmessage__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__cpqpricingmessage__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__currencypaymentmode__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__currencypaymentmode__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__disconnectdate__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__disconnectdate__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__effectivebaseonetimetotal__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__effectivebaseonetimetotal__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__effectivebaserecurringtotal__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__effectivebaserecurringtotal__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__effectiveonetimecosttotal__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__effectiveonetimecosttotal__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__effectiveonetimeloyaltytotal__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__effectiveonetimeloyaltytotal__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__effectiveonetimetotal__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__effectiveonetimetotal__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__effectivequantity__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__effectivequantity__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__effectiverecurringcosttotal__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__effectiverecurringcosttotal__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__effectiverecurringtotal__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__effectiverecurringtotal__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__effectiveusagecosttotal__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__effectiveusagecosttotal__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__effectiveusagepricetotal__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__effectiveusagepricetotal__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__effectiveusagequantity__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__effectiveusagequantity__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__filter__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__filter__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__financedamounttotal__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__financedamounttotal__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__financedamount__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__financedamount__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__financedinstallmentamount__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__financedinstallmentamount__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__incartquantitymap__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__incartquantitymap__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__ispriced__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__ispriced__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__isproducttrackagreement__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__isproducttrackagreement__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__isvalidated__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__isvalidated__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__itemname__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__itemname__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__jsonattribute__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__jsonattribute__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__jsonnode__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__jsonnode__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__lastpricedat__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__lastpricedat__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__linenumber__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__linenumber__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__lockedby__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__lockedby__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__lockedfor__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__lockedfor__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__modification__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__modification__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__onetimecalculatedprice__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__onetimecalculatedprice__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__onetimecharge__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__onetimecharge__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__onetimecosttotal__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__onetimecosttotal__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__onetimecost__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__onetimecost__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__onetimediscountprice__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__onetimediscountprice__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__onetimeloyaltyprice__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__onetimeloyaltyprice__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__onetimeloyaltytotal__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__onetimeloyaltytotal__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__onetimemanualdiscount__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__onetimemanualdiscount__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__onetimemargin__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__onetimemargin__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__onetimetotal__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__onetimetotal__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__overagecalculatedprice__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__overagecalculatedprice__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__overagecharge__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__overagecharge__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__overagediscountprice__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__overagediscountprice__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__overagemanualdiscount__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__overagemanualdiscount__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__overagetotal__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__overagetotal__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__overageuom__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__overageuom__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__parentitemid__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__parentitemid__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__premisesid__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__premisesid__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__pricinglogdata__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__pricinglogdata__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__priorquotelineitemid__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__priorquotelineitemid__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__product2id__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__product2id__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__productattribxn__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__productattribxn__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__productgroupkey__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__productgroupkey__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__producthierarchygroupkeypath__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__producthierarchygroupkeypath__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__producthierarchypath__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__producthierarchypath__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__provisioningstatus__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__provisioningstatus__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__query__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__query__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__quotegroupid__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__quotegroupid__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__quotememberid__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__quotememberid__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__recurringcalculatedprice__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__recurringcalculatedprice__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__recurringcharge__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__recurringcharge__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__recurringcosttotal__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__recurringcosttotal__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__recurringcost__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__recurringcost__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__recurringdiscountprice__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__recurringdiscountprice__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__recurringmanualdiscount__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__recurringmanualdiscount__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__recurringmargin__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__recurringmargin__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__recurringtotal__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__recurringtotal__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__recurringuom__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__recurringuom__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__recurring_uom__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__recurring_uom__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__relationshiptype__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__relationshiptype__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__reliesonitemid__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__reliesonitemid__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__rootitemid__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__rootitemid__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__sequencenumber__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__sequencenumber__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__serialnumber__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__serialnumber__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__serviceaccountid__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__serviceaccountid__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__servicedate__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__servicedate__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__serviceidentifier__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__serviceidentifier__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__servicepointid__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__servicepointid__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__sourcelinenumber__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__sourcelinenumber__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__subaction__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__subaction__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__subscriptionid__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__subscriptionid__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__usagecosttotal__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__usagecosttotal__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__usagemargin__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__usagemargin__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__usagemeasurementid__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__usagemeasurementid__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__usagepricetotal__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__usagepricetotal__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__usagequantity__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__usagequantity__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__usageunitcost__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__usageunitcost__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__usageunitprice__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__usageunitprice__c`",
            "string",
        ),
        (
            "`(qli) vlocity_cmt__validationdate__c`",
            "string",
            "`(mppNqli) (qli) vlocity_cmt__validationdate__c`",
            "string",
        ),
        (
            "`(qli) swm_discounting_exception__c`",
            "string",
            "`(mppNqli) (qli) swm_discounting_exception__c`",
            "string",
        ),
        (
            "`(qli) swm_gross_unit_cost__c`",
            "string",
            "`(mppNqli) (qli) swm_gross_unit_cost__c`",
            "string",
        ),
        (
            "`(qli) is_bonus_product__c`",
            "string",
            "`(mppNqli) (qli) is_bonus_product__c`",
            "string",
        ),
        (
            "`(qli) swm_market_price__c`",
            "string",
            "`(mppNqli) (qli) swm_market_price__c`",
            "string",
        ),
        (
            "`(qli) swm_floor_rate__c`",
            "string",
            "`(mppNqli) (qli) swm_floor_rate__c`",
            "string",
        ),
        (
            "`(qli) swm_rate_card__c`",
            "string",
            "`(mppNqli) (qli) swm_rate_card__c`",
            "string",
        ),
        (
            "`(qli) parent_qli__c`",
            "string",
            "`(mppNqli) (qli) parent_qli__c`",
            "string",
        ),
        (
            "`(qli) targeting_premium__c`",
            "string",
            "`(mppNqli) (qli) targeting_premium__c`",
            "string",
        ),
        (
            "`(qli) gross_unit_cost_with_premium__c`",
            "string",
            "`(mppNqli) (qli) gross_unit_cost_with_premium__c`",
            "string",
        ),
        (
            "`(qli) swm_sponsorship_product__c`",
            "string",
            "`(mppNqli) (qli) swm_sponsorship_product__c`",
            "string",
        ),
        ("`(qli) buy_type__c`", "string", "`(mppNqli) (qli) buy_type__c`", "string"),
        ("`(qli) filename`", "string", "`(mppNqli) (qli) filename`", "string"),
        (
            "`(qli) function_name`",
            "string",
            "`(mppNqli) (qli) function_name`",
            "string",
        ),
        (
            "`(qli) function_version`",
            "string",
            "`(mppNqli) (qli) function_version`",
            "string",
        ),
        (
            "`(qli) aws_request_id`",
            "string",
            "`(mppNqli) (qli) aws_request_id`",
            "string",
        ),
        ("`(qli) appflow_id`", "string", "`(mppNqli) (qli) appflow_id`", "string"),
        (
            "`(qli) processed_ts`",
            "timestamp",
            "`(mppNqli) (qli) processed_ts`",
            "timestamp",
        ),
        (
            "`(qli) swm_optimize__c`",
            "string",
            "`(mppNqli) (qli) swm_optimize__c`",
            "string",
        ),
        (
            "`(qli) swm_read_optimize__c`",
            "string",
            "`(mppNqli) (qli) swm_read_optimize__c`",
            "string",
        ),
        (
            "`(qli) swm_total_market_price__c`",
            "string",
            "`(mppNqli) (qli) swm_total_market_price__c`",
            "string",
        ),
        ("`(qli) swm_gst__c`", "string", "`(mppNqli) (qli) swm_gst__c`", "string"),
        (
            "`(qli) swm_otc_gst__c`",
            "string",
            "`(mppNqli) (qli) swm_otc_gst__c`",
            "string",
        ),
        (
            "`(qli) swm_gst_value__c`",
            "string",
            "`(mppNqli) (qli) swm_gst_value__c`",
            "string",
        ),
        (
            "`(qli) production_system__c`",
            "string",
            "`(mppNqli) (qli) production_system__c`",
            "string",
        ),
        (
            "`(qli) impliedtotal__c`",
            "string",
            "`(mppNqli) (qli) impliedtotal__c`",
            "string",
        ),
        (
            "`(qli) totaladtime__c`",
            "string",
            "`(mppNqli) (qli) totaladtime__c`",
            "string",
        ),
        (
            "`(qli) bonus_ad_time__c`",
            "string",
            "`(mppNqli) (qli) bonus_ad_time__c`",
            "string",
        ),
        (
            "`(qli) costperratingpoint__c`",
            "string",
            "`(mppNqli) (qli) costperratingpoint__c`",
            "string",
        ),
        (
            "`(qli) grossratingpoint__c`",
            "string",
            "`(mppNqli) (qli) grossratingpoint__c`",
            "string",
        ),
        (
            "`(qli) paidadtime__c`",
            "string",
            "`(mppNqli) (qli) paidadtime__c`",
            "string",
        ),
        (
            "`(qli) swm_is_sponsorship__c`",
            "string",
            "`(mppNqli) (qli) swm_is_sponsorship__c`",
            "string",
        ),
        (
            "`(qli) is_roadblock_product__c`",
            "string",
            "`(mppNqli) (qli) is_roadblock_product__c`",
            "string",
        ),
        (
            "`(qli) swm_approval_status__c`",
            "string",
            "`(mppNqli) (qli) swm_approval_status__c`",
            "string",
        ),
        (
            "`(qli) swm_quote_owner__c`",
            "string",
            "`(mppNqli) (qli) swm_quote_owner__c`",
            "string",
        ),
        (
            "`(qli) swm_prior_oli_id__c`",
            "string",
            "`(mppNqli) (qli) swm_prior_oli_id__c`",
            "string",
        ),
        ("`(qli) partition_0`", "string", "`(mppNqli) (qli) partition_0`", "string"),
        ("`(qli) partition_1`", "string", "`(mppNqli) (qli) partition_1`", "string"),
        ("`(qli) partition_2`", "string", "`(mppNqli) (qli) partition_2`", "string"),
        ("`(qli) partition_3`", "string", "`(mppNqli) (qli) partition_3`", "string"),
    ],
    transformation_ctx="RenamedMppQuoteLineItem_node1657713309822",
)

# Script generated for node Join
Join_node1657713249229 = Join.apply(
    frame1=Join_node1657712000396,
    frame2=RenamedMppQuoteLineItem_node1657713309822,
    keys1=["`(u) id`"],
    keys2=["`(mppNqli) createdbyid`"],
    transformation_ctx="Join_node1657713249229",
)

# Script generated for node Apply Mapping
ApplyMapping_node1657713418132 = ApplyMapping.apply(
    frame=Join_node1657713249229,
    mappings=[
        (
            "`(mppNqli) vlocity_cmt__quotelineitemid__c`",
            "string",
            "Production_Line_Item_Id",
            "string",
        ),
        (
            "`(mppNqli) (qli) vlocity_cmt__itemname__c`",
            "string",
            "Production Line Item Name",
            "string",
        ),
        (
            "vlocity_cmt__adserverid__c",
            "string",
            "Ad Slot ID",
            "string",
        ),
        ("name", "string", "Ad Slot Name", "string"),
        
        # Generated
        
    ],
    transformation_ctx="ApplyMapping_node1657713418132",
)

# Convert to a dataframe and partition based on "partition_col"
partitioned_dataframe = ApplyMapping_node1657713418132.toDF().coalesce(1)

partitioned_dataframe = partitioned_dataframe \
                            .withColumn("OP1_Production_Line_Item_Id",lit(None)) \
                            .withColumn("OP1_Ad Slot ID",lit(None))

# Convert back to a DynamicFrame for further processing.
partitioned_dynamicframe = DynamicFrame.fromDF(partitioned_dataframe, glueContext, "partitioned_df")

# Script generated for node Amazon S3
Synth_Production_Line_Item_PO = glueContext.write_dynamic_frame.from_options(
    frame=partitioned_dynamicframe,
    connection_type="s3",
    format="csv",
    connection_options={
        "path": "s3://swmi-etldev-sf-to-dw-dwmock",
        "partitionKeys": [],
    },
    transformation_ctx="Synth_Production_Line_Item_PO",
)

job.commit()

###############################################################
## Clowning the existing file and deleting the old file.    ###
###############################################################

bucket_name = "swmi-etldev-sf-to-dw-dwmock"
filename = "Synth-Production_Line_Item_PO" + "_" + str(datetime.now().strftime("%Y-%m-%d %H%M%S"))

client = boto3.client('s3')
#getting all the content/file inside the bucket. 
names = client.list_objects_v2(Bucket=bucket_name)["Contents"]

#Find out the file which have part-000* in it's Key
particulars = [name['Key'] for name in names if 'part-r-000' in name['Key']]

particular = particulars[0]
client.copy_object(Bucket=bucket_name, CopySource=bucket_name + "/" + particular, Key=filename + ".csv")
client.delete_object(Bucket=bucket_name, Key=particular)
