AWSTemplateFormatVersion: 2010-09-09
Description: Configure Public Subnet NACLs

Parameters:
  VPCId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /networking/vpc/id

  VPCCidr:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /networking/VPC/cidr

  RestrictedSummarisedCIDRParameter:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /networking/VPC/restrictedcidr

  PrivateSummarisedCIDRParameter:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /networking/VPC/privatecidr

  PublicSubnet1Id:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /networking/publicsubnet1/id

  PublicSubnet2Id:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /networking/publicsubnet2/id

  PublicSubnet3Id:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /networking/publicsubnet3/id

  PrivateSubnet1Id:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /networking/privatesubnet1/id

  PrivateSubnet2Id:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /networking/privatesubnet2/id

  PrivateSubnet3Id:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /networking/privatesubnet3/id

  RestrictedSubnet1Id:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /networking/restrictedSubnet1/id

  RestrictedSubnet2Id:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /networking/restrictedSubnet2/id

  RestrictedSubnet3Id:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /networking/restrictedSubnet3/id

Resources:
# Public NACL
  NetworkAclPublicIn:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref VPCId
      Tags:
        - Key: Name
          Value: Public-NACL

  SubnetNetworkAclAssociationPublicIn1:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref NetworkAclPublicIn
      SubnetId: !Ref PublicSubnet1Id

  SubnetNetworkAclAssociationPublicIn2:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref NetworkAclPublicIn
      SubnetId: !Ref PublicSubnet2Id

  SubnetNetworkAclAssociationPublicIn3:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref NetworkAclPublicIn
      SubnetId: !Ref PublicSubnet3Id

  NetworkAclEntryPublicInInbound10080:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: !Ref VPCCidr
      Egress: false
      NetworkAclId: !Ref NetworkAclPublicIn
      Protocol: 6
      PortRange:
        From: 80
        To: 80
      RuleAction: allow
      RuleNumber: 10080

  NetworkAclEntryPublicInInbound10443:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: !Ref VPCCidr
      Egress: false
      NetworkAclId: !Ref NetworkAclPublicIn
      Protocol: 6
      PortRange:
        From: 443
        To: 443
      RuleAction: allow
      RuleNumber: 10443

  NetworkAclEntryPublicInInbound15000:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: false
      NetworkAclId: !Ref NetworkAclPublicIn
      Protocol: 6
      PortRange:
        From: 22
        To: 22
      RuleAction: allow
      RuleNumber: 15000

  NetworkAclEntryPublicInInbound20000:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: false
      NetworkAclId: !Ref NetworkAclPublicIn
      Protocol: 6
      PortRange:
        From: 1024
        To: 65535
      RuleAction: allow
      RuleNumber: 20000

  NetworkAclEntryPublicInOutbound10000:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: !Ref VPCCidr
      Egress: true
      NetworkAclId: !Ref NetworkAclPublicIn
      Protocol: 6
      PortRange:
        From: 1024
        To: 65535
      RuleAction: allow
      RuleNumber: 10000

  NetworkAclEntryPublicInOutbound10080:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: true
      NetworkAclId: !Ref NetworkAclPublicIn
      Protocol: 6
      PortRange:
        From: 80
        To: 80
      RuleAction: allow
      RuleNumber: 10080

  NetworkAclEntryPublicInOutbound10443:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: true
      NetworkAclId: !Ref NetworkAclPublicIn
      Protocol: 6
      PortRange:
        From: 443
        To: 443
      RuleAction: allow
      RuleNumber: 10443

# Private NACL
  NetworkAclPrivateIn:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref VPCId
      Tags:
        - Key: Name
          Value: Private-NACL

  SubnetNetworkAclAssociationPrivateIn1:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref NetworkAclPrivateIn
      SubnetId: !Ref PrivateSubnet1Id

  SubnetNetworkAclAssociationPrivateIn2:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref NetworkAclPrivateIn
      SubnetId: !Ref PrivateSubnet2Id

  SubnetNetworkAclAssociationPrivateIn3:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref NetworkAclPrivateIn
      SubnetId: !Ref PrivateSubnet3Id

  NetworkAclEntryPrivateInInbound10000:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: !Ref VPCCidr
      Egress: false
      NetworkAclId: !Ref NetworkAclPrivateIn
      Protocol: -1
      RuleAction: allow
      RuleNumber: 10000

  NetworkAclEntryPrivateInInbound20000:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: false
      NetworkAclId: !Ref NetworkAclPrivateIn
      Protocol: 6
      PortRange:
        From: 1024
        To: 65535
      RuleAction: allow
      RuleNumber: 20000

  NetworkAclEntryPrivateInOutbound10000:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: !Ref VPCCidr
      Egress: true
      NetworkAclId: !Ref NetworkAclPrivateIn
      Protocol: -1
      RuleAction: allow
      RuleNumber: 10000

  NetworkAclEntryPrivateInOutbound10080:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: true
      NetworkAclId: !Ref NetworkAclPrivateIn
      Protocol: 6
      PortRange:
        From: 80
        To: 80
      RuleAction: allow
      RuleNumber: 10080

  NetworkAclEntryPrivateInOutbound10443:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: true
      NetworkAclId: !Ref NetworkAclPrivateIn
      Protocol: 6
      PortRange:
        From: 443
        To: 443
      RuleAction: allow
      RuleNumber: 10443

# Restricted NACL
  NetworkAclRestrictedIn:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref VPCId
      Tags:
        - Key: Name
          Value: Restricted-NACL

  SubnetNetworkAclAssociationRestrictedIn1:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref NetworkAclRestrictedIn
      SubnetId: !Ref RestrictedSubnet1Id

  SubnetNetworkAclAssociationRestrictedIn2:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref NetworkAclRestrictedIn
      SubnetId: !Ref RestrictedSubnet2Id

  SubnetNetworkAclAssociationRestrictedIn3:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref NetworkAclRestrictedIn
      SubnetId: !Ref RestrictedSubnet3Id

  NetworkAclEntryRestrictedInInbound10000:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: !Ref RestrictedSummarisedCIDRParameter
      Egress: false
      NetworkAclId: !Ref NetworkAclRestrictedIn
      Protocol: -1
      RuleAction: allow
      RuleNumber: 10000

  NetworkAclEntryRestrictedInInbound10050:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: !Ref PrivateSummarisedCIDRParameter
      Egress: false
      NetworkAclId: !Ref NetworkAclRestrictedIn
      Protocol: -1
      RuleAction: allow
      RuleNumber: 10050

  NetworkAclEntryRestrictedInOutbound10000:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: !Ref RestrictedSummarisedCIDRParameter
      Egress: true
      NetworkAclId: !Ref NetworkAclRestrictedIn
      Protocol: -1
      RuleAction: allow
      RuleNumber: 10000

  NetworkAclEntryRestrictedInOutbound10050:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: !Ref PrivateSummarisedCIDRParameter
      Egress: true
      NetworkAclId: !Ref NetworkAclRestrictedIn
      Protocol: -1
      RuleAction: allow
      RuleNumber: 10050