trigger: none
pool:
  vmImage: ubuntu-20.04

parameters:
  - name: env
    displayName: Environment
    type: string
    values:
      - apidev
      - etldev
      - sit
      - uat
      - prod
  - name: services
    displayName: Services to build
    type: object
    default:
      - tech1-client
      - tech1-router
      - gam-client
      - gam-router
  - name: costCenter
    displayName: "Tag: Cost Center"
    type: string
    default: "7IT"
    values:
      - 7IT
  - name: project
    displayName: "Tag: Project"
    type: string
    default: "SWM Integration"
  - name: role
    displayName: "Tag: Role"
    type: string
    default: "Azure DevOps pipeline"
  - name: repository
    displayName: "Tag: Repository"
    type: string
    default: "SWM Integration"
  - name: criticality
    displayName: "Tag: Criticality"
    type: string
    default: "Critical"
    values:
      - Critical
      - High
      - Medium
      - Low
  - name: pii
    displayName: "Tag: PII"
    type: string
    default: "no"
    values:
      - yes
      - no
  - name: securityClassification
    displayName: "Tag: Security Classification"
    type: string
    default: "Critical"
    values:
      - Critical
      - High
      - Medium
      - Low


variables:
  - name: serviceConnection
    ${{ if in(parameters.env, 'apidev', 'etldev') }}:
      value: AwsDev
    ${{ elseif in(parameters.env, 'uat', 'sit') }}:
      value: AwsNonProd
    ${{ elseif in(parameters.env, 'prod') }}:
      value: AwsProd
  - name: region
    value: ap-southeast-2
  - name: specfile
    value: openapi-oas30.yaml

stages:
  - ${{ each service in parameters.services }}:
      - stage: ${{ replace(service, '-', '_') }}
        dependsOn: []
        displayName: Deploy ${{ service }}-service Lambda
        jobs:
          - template: ../templates/lambda-build.yaml
            parameters:
              lambda: api/${{ service }}-service
              env: ${{ parameters.env }}
              serviceConnection: ${{ variables.serviceConnection }}
          - job: updateStack
            displayName: Deploy ${{ service }}-service Lambda Stack
            dependsOn: buildDeploy
            variables:
              lambdaVersion: $[ dependencies.buildDeploy.outputs['outputVersion.lambdaVersion'] ]
            steps:
              - task: CloudFormationCreateOrUpdateStack@1
                displayName: Update Stack
                inputs:
                  awsCredentials: ${{ variables.serviceConnection }}
                  regionName: ${{ variables.region }}
                  stackName: ${{ parameters.env }}-${{ service }}-service
                  capabilityIAM: true
                  capabilityNamedIAM: true
                  capabilityAutoExpand: true
                  templateFile: cfn/templates/api/${{ service }}-service.yaml
                  templateParametersSource: inline
                  templateParameters: |
                    - ParameterKey: EnvPrefix
                      ParameterValue: ${{ parameters.env }}
                    - ParameterKey: LambdaVersion
                      ParameterValue: $(lambdaVersion)
                  tags: |
                    CostCenter=${{ parameters.costCenter }}
                    Environment=${{ parameters.env }}
                    IACReleaseNumber=$(Build.SourceVersion)
                    LastUpdatedBy=$(Build.QueuedBy)
                    Project=${{ parameters.project }}
                    Role=${{ parameters.role }}
                    Repository=${{ parameters.repository }}
                    Criticality=${{ parameters.criticality }}
                    PII=${{ parameters.pii }}
                    SecurityClassification=${{ parameters.securityClassification }}

  - stage: deployApiGatewayStack
    displayName: Deploy API gateway stack
    dependsOn:
      - ${{ each service in parameters.services }}:
          - ${{ replace(service, '-', '_') }}
    jobs:
      - job: createOrUpdateApiGatewayStack
        displayName: Create or update API gateway stack
        steps:
          - task: SystemsManagerGetParameter@1
            inputs:
              awsCredentials: ${{ variables.serviceConnection }}
              regionName: ${{ variables.region }}
              readMode: single
              parameterName: ProjPrefix
              singleNameTransform: custom
              customVariableName: projPrefix

          - task: S3Upload@1
            inputs:
              awsCredentials: ${{ variables.serviceConnection }}
              regionName: ${{ variables.region }}
              bucketName: $(projPrefix)-${{ parameters.env }}-sourcecode
              sourceFolder: resources/openapi/apigateway
              globExpressions: ${{ variables.specfile }}
              targetFolder: openapi-specs
              keyManagement: awsManaged
              kmsMasterKeyId: alias/${{ parameters.env }}-s3

          - task: CloudFormationCreateOrUpdateStack@1
            inputs:
              awsCredentials: ${{ variables.serviceConnection }}
              regionName: ${{ variables.region }}
              stackName: ${{ parameters.env }}-api-apigateway
              capabilityIAM: true
              capabilityNamedIAM: true
              capabilityAutoExpand: true
              templateFile: cfn/templates/api/apigateway.yaml
              templateParametersSource: inline
              templateParameters: |
                - ParameterKey: EnvPrefix
                  ParameterValue: ${{ parameters.env }}
                - ParameterKey: CodeBucket
                  ParameterValue: $(projPrefix)-${{ parameters.env }}-sourcecode
                - ParameterKey: ApiSpecKey
                  ParameterValue: openapi-specs/${{ variables.specfile }}
              tags: |
                CostCenter=${{ parameters.costCenter }}
                Environment=${{ parameters.env }}
                IACReleaseNumber=$(Build.SourceVersion)
                LastUpdatedBy=$(Build.QueuedBy)
                Project=${{ parameters.project }}
                Role=${{ parameters.role }}
                Repository=${{ parameters.repository }}
                Criticality=${{ parameters.criticality }}
                PII=${{ parameters.pii }}
                SecurityClassification=${{ parameters.securityClassification }}