trigger: none

parameters:
  - name: env
    displayName: Environment
    type: string
    values:
      - apidev
      - etldev
      - sit
      - uat
      - prod
  - name: costCenter
    displayName: "Tag: Cost Center"
    type: string
    default: "7IT"
    values:
      - 7IT
  - name: project
    displayName: "Tag: Project"
    type: string
    default: "SWM Integration"
  - name: role
    displayName: "Tag: Role"
    type: string
    default: "Azure DevOps pipeline"
  - name: repository
    displayName: "Tag: Repository"
    type: string
    default: "SWM Integration"
  - name: criticality
    displayName: "Tag: Criticality"
    type: string
    default: "Critical"
    values:
      - Critical
      - High
      - Medium
      - Low
  - name: pii
    displayName: "Tag: PII"
    type: string
    default: "no"
    values:
      - yes
      - no
  - name: securityClassification
    displayName: "Tag: Security Classification"
    type: string
    default: "Critical"
    values:
      - Critical
      - High
      - Medium
      - Low

variables:
  - name: serviceConnection
    ${{ if in(parameters.env, 'etldev', 'apidev') }}:
      value: AwsDev
    ${{ elseif in(parameters.env, 'uat', 'sit') }}:
      value: AwsNonProd
    ${{ elseif in(parameters.env, 'prod') }}:
      value: AwsProd
  - name: region
    value: ap-southeast-2

stages:
  - stage: billingLambda
    displayName: Deploy Billing Extract Lambda
    jobs:
      - template: ../templates/lambda-build.yaml
        parameters:
          lambda: sf-to-t1/billing
          env: ${{ parameters.env }}
          serviceConnection: ${{ variables.serviceConnection }}

      - job: updateEventStack
        displayName: Deploy Billing Event Stack
        dependsOn: buildDeploy
        variables:
          lambdaVersion: $[ dependencies.buildDeploy.outputs['outputVersion.lambdaVersion'] ]
        steps:
          - task: CloudFormationCreateOrUpdateStack@1
            displayName: Update Stack
            inputs:
              awsCredentials: ${{ variables.serviceConnection }}
              regionName: ${{ variables.region }}
              stackName: ${{ parameters.env }}-sf-to-t1-billing-event
              capabilityIAM: true
              capabilityNamedIAM: true
              capabilityAutoExpand: true
              templateFile: cfn/templates/sf-to-t1/billingEvent.yaml
              templateParametersSource: inline
              templateParameters: |
                - ParameterKey: EnvPrefix
                  ParameterValue: ${{ parameters.env }}
                - ParameterKey: LambdaVersion
                  ParameterValue: $(lambdaVersion)
              tags: |
                CostCenter=${{ parameters.costCenter }}
                Environment=${{ parameters.env }}
                IACReleaseNumber=$(Build.SourceVersion)
                LastUpdatedBy=$(Build.QueuedBy)
                Project=${{ parameters.project }}
                Role=${{ parameters.role }}
                Repository=${{ parameters.repository }}
                Criticality=${{ parameters.criticality }}
                PII=${{ parameters.pii }}
                SecurityClassification=${{ parameters.securityClassification }}