trigger: none
pool:
  vmImage: ubuntu-20.04

parameters:
  - name: stackName
    displayName: Stack Name
    type: string
    values:
      - azureDevOps
      - vpcSubnets
      - vgw
      - resourcePolicies
      - route53
      - sftp-server
      - ecr-account-wide
  - name: account
    displayName: Account
    type: string
    values:
      - dev
      - nonprod
      - prod
  - name: costCenter
    displayName: "Tag: Cost Center"
    type: string
    default: "7IT"
    values:
      - 7IT
  - name: project
    displayName: "Tag: Project"
    type: string
    default: "SWM Integration"
  - name: role
    displayName: "Tag: Role"
    type: string
    default: "Azure DevOps pipeline"
  - name: repository
    displayName: "Tag: Repository"
    type: string
    default: "SWM Integration"
  - name: criticality
    displayName: "Tag: Criticality"
    type: string
    default: "Critical"
    values:
      - Critical
      - High
      - Medium
      - Low
  - name: pii
    displayName: "Tag: PII"
    type: string
    default: "no"
    values:
      - yes
      - no
  - name: securityClassification
    displayName: "Tag: Security Classification"
    type: string
    default: "Critical"
    values:
      - Critical
      - High
      - Medium
      - Low

variables:
  - name: serviceConnection
    ${{ if eq(parameters.account, 'dev') }}:
      value: AwsDev
    ${{ elseif eq(parameters.account, 'nonprod') }}:
      value: AwsNonProd
    ${{ elseif eq(parameters.account, 'prod') }}:
      value: AwsProd
  - name: region
    value: ap-southeast-2

steps:
  - task: CloudFormationCreateOrUpdateStack@1
    inputs:
      awsCredentials: ${{ variables.serviceConnection }}
      regionName: ${{ variables.region }}
      stackName: ${{ parameters.account }}-${{ parameters.stackName }}
      capabilityIAM: true
      capabilityNamedIAM: true
      capabilityAutoExpand: true
      templateFile: cfn/templates/platform/account-${{ parameters.stackName }}.yaml
      tags: |
        CostCenter=${{ parameters.costCenter }}
        Environment=${{ parameters.env }}
        IACReleaseNumber=$(Build.SourceVersion)
        LastUpdatedBy=$(Build.QueuedBy)
        Project=${{ parameters.project }}
        Role=${{ parameters.role }}
        Repository=${{ parameters.repository }}
        Criticality=${{ parameters.criticality }}
        PII=${{ parameters.pii }}
        SecurityClassification=${{ parameters.securityClassification }}